var createError = require('http-errors');
var express = require('express');
var path = require('path');
var indexRouter = require('./routes/index');
var http = require('http');
var app = express();
var port = (process.env.PORT || '3000');
var server = http.createServer(app);


/**
 * All the code below was auto generated by Eclipse IDE when setting up a EJS template
 * Create HTTP server.
 */


server.listen(port);
server.on('listening', onListening);
app.set('port', port);
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
app.use('/', indexRouter);


function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string'
        ? 'pipe ' + addr
        : 'port ' + addr.port;
}

module.exports = app;
