var createError = require('http-errors');
var express = require('express');
var path = require('path');

var http = require('http');
var app = express();
var port = (process.env.PORT || '3000');
var server = http.createServer(app);

/**
 * Routes to each pages 
 */

var indexRouter = require('./routes/index');
var fav = require('./routes/fav');
var library = require('./routes/library');
var pictures = require('./routes/pictures');
var new_book = require('./routes/new_book');
app.use('/', indexRouter);
app.use('/fav', fav);
app.use('/library', library);
app.use('/pictures', pictures);
app.use('/new_book', new_book);
/**
 * All the code below was auto generated by Eclipse IDE when setting up a EJS template
 * Create HTTP server.
 */


server.listen(port);
server.on('listening', onListening);
app.set('port', port);
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));



function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string'
        ? 'pipe ' + addr
        : 'port ' + addr.port;
}

module.exports = app;
